### ISSUE TITLE
ssh won't connect LF1000

### ISSUE THREAD

**Issue by HighOnVoltage** [mac2612/sshflash#7]
When I run remote_flash.sh for retroleap it's given me an error stating it can't connect. 
I believe it has to do with this project, but really unsure what's missing. 
My python version is 2.7.18
OS: Ubuntu Cinnamon 22.04.1
Kernel: 5.15.0-60-generic

Enter choice (1 - 4)2
Writing CBF file.
CBF File Summary:
kernel_crc:	0xd0924a78
cbf_magic:	0x9abcdef0
cbf_version:	0x00000001
kernel_load:	0x00100000
kernel_jump:	0x00100000
sum_crc:	0x9a9e4da8
size:		0x00229354
Compressed: 	 True
Booting the Surgeon environment...
Writing CBF file.
CBF File Summary:
kernel_crc:	0x9b9857a1
cbf_magic:	0x9abcdef0
cbf_version:	0x00000001
kernel_load:	0x00100000
kernel_jump:	0x00100000
sum_crc:	0x9aea2a14
size:		0x0056f4e0
Compressed: 	 True
Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
    do_surgeon_boot(sys.argv[1])
  File "boot_surgeon.py", line 16, in do_surgeon_boot
    pager_client.upload(path)
  File "/home/tradietrev/Downloads/sshflash/pager.py", line 114, in upload
    self.rerror(e)
  File "/home/tradietrev/Downloads/sshflash/pager.py", line 64, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: [Errno 2] No such file or directory
Done! Waiting for Surgeon to come up...Done!
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Detected Kernel partition= RFS Partition=
Flashing the kernel...ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Done flashing the kernel!
Flashing the root filesystem...ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Writing rootfs image...
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Done flashing the root filesystem!
Do you want to format the roms partition? (You should do this on the first flash of retroleap) (y/n)y
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Done! Rebooting the host.
ssh: connect to host 169.254.8.1 port 22: No route to host

Any advice would be greatly appreciated, there's come good efforts put into these projects of yours.

**Comment by niutech** [comment]
Which version of sshflash and retroleap? I can confirm flashing LF1000 works for sshflash-2.0-alpha4 and retroleap_v2.0.0-alpha10.
